# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [27]:
mat1 = np.array([[1,2,10],[3,4,21], [4,5,99]])
mat2 = np.array([[1,2,10],[3,4,21], [4,5,99]])
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)

print("\nAddition\n------------------\n", mat1+mat2)

print("\nMultiplication\n------------------\n", mat1*mat2)

print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", mat1,mat2)

print("\nAddition of a scalar (100)\n-------------------------\n", mat1+100,mat2+100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", (mat1)**3,(mat2)**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.square(mat1))


1st Matrix of random single-digit numbers
----------------------------------------
 [[ 1  2 10]
 [ 3  4 21]
 [ 4  5 99]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[ 1  2 10]
 [ 3  4 21]
 [ 4  5 99]]

Addition
------------------
 [[  2   4  20]
 [  6   8  42]
 [  8  10 198]]

Multiplication
------------------
 [[   1    4  100]
 [   9   16  441]
 [  16   25 9801]]

Division
------------------
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ 1  2 10]
 [ 3  4 21]
 [ 4  5 99]] [[ 1  2 10]
 [ 3  4 21]
 [ 4  5 99]]

Addition of a scalar (100)
-------------------------
 [[101 102 110]
 [103 104 121]
 [104 105 199]] [[101 102 110]
 [103 104 121]
 [104 105 199]]

Exponentiation, matrix cubed here
----------------------------------------
 [[     1      8   1000]
 [    27     64   9261]
 [    64    125 970299]] [[     1      8   1000]
 [    27     64   9261]
 [    64    125 970299]]

Exponentiation,

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [55]:
from numpy.random import randint as ri
mat1 = np.random.rand(1,100,20)
mat2 = np.random.rand(1,100,30)

print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)

print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=0))

print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1, axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat1, axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))

mat1 = np.random.randint(1,100)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[[0.77936267 0.52314891 0.71715175 ... 0.65619983 0.23264306 0.47272579]
  [0.43647459 0.06062313 0.83744773 ... 0.1302815  0.72313514 0.84511292]
  [0.70055297 0.74891642 0.60214543 ... 0.02649293 0.21853959 0.52500514]
  ...
  [0.56431036 0.03669153 0.14365805 ... 0.29545512 0.26211384 0.69737073]
  [0.78429357 0.41083593 0.07522471 ... 0.10975911 0.18227008 0.11844106]
  [0.03720153 0.29631981 0.49903123 ... 0.34514371 0.9486311  0.54240275]]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[[0.60995532 0.36477225 0.07813139 ... 0.02183887 0.34957236 0.29002701]
  [0.8194461  0.06680149 0.71975872 ... 0.18888098 0.73859378 0.86343618]
  [0.18594419 0.98978904 0.91999048 ... 0.44830611 0.4672023  0.968145  ]
  ...
  [0.49195225 0.0839468  0.56521543 ... 0.20176163 0.88494176 0.36190986]
  [0.79100052 0.40764605 0.06344692 ... 0.23939881 0

In [56]:
from numpy.random import randint as ri
mat1 = np.random.rand(3,3)
mat2 = np.random.rand(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[0.99313093 0.65849878 0.59532065]
 [0.33999413 0.38166617 0.78051174]
 [0.45316134 0.7139557  0.5613737 ]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[0.46262927 0.59969724 0.86737996]
 [0.45266435 0.78446655 0.28854591]
 [0.04774737 0.7443909  0.00908858]]


###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [57]:
##Solution
mat1.reshape(9,1)

array([[0.99313093],
       [0.65849878],
       [0.59532065],
       [0.33999413],
       [0.38166617],
       [0.78051174],
       [0.45316134],
       [0.7139557 ],
       [0.5613737 ]])

### 4.Sort

In [60]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [43 36 15 18 79 56 31 45 82 71]

Here is the sorted vector
 -------------------------------------------------- 
 [15 18 31 36 43 45 56 71 79 82]


In [61]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[88 60 89 60 22]
 [69 63 91 81 50]
 [97 63 19 94 26]
 [54 20 22 72 21]
 [85 18 90 19 80]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[22 60 60 88 89]
 [50 63 69 81 91]
 [19 26 63 94 97]
 [20 21 22 54 72]
 [18 19 80 85 90]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[54 18 19 19 21]
 [69 20 22 60 22]
 [85 60 89 72 26]
 [88 63 90 81 50]
 [97 63 91 94 80]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [67]:
# Fill the following ***** with appropriate solution.
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", a.max())
print("Max of b:",b.max())


print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

print("Min of a:", a.min())
print("Min of b:",b.min())


print("Min of a location:", a.argmin())
print("Min of b location:", b.argmin())
print("Min of c location:", b.argmin())



a: [77 69 68 76 56 99 23 73 22 89 69 33 27 32 98 34 13 23  7 50 16  9 28 90
 97 91 37  3  3 28]
b: [[[77 69 68 76 56]
  [99 23 73 22 89]
  [69 33 27 32 98]]

 [[34 13 23  7 50]
  [16  9 28 90 97]
  [91 37  3  3 28]]]
c: [[77 69 68 76 56]
 [99 23 73 22 89]
 [69 33 27 32 98]
 [34 13 23  7 50]
 [16  9 28 90 97]
 [91 37  3  3 28]]
Max of a: 99
Max of b: 99
Max of a location: 5
Max of b location: 5
Max of c location: 5
Min of a: 3
Min of b: 3
Min of a location: 27
Min of b location: 27
Min of c location: 27


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [77]:

mat1 = np.random.randint(1,50)
mat2 = np.random.randint(1,25)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1) )


print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 49

2nd Matrix of random single-digit numbers
----------------------------------------
 8

Sq-root of 1st matrix using np
------------------
 7.0

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 1.9073465724950998e+21

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 1.6901960800285136

Modulo reminder using np
 -------------------------------------------------- 
 1


### 7.Generating matrices from distributions

In [79]:

print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.36837647 0.48632922 0.3797699 ]
 [0.80677961 0.25366211 0.61062068]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.44345033 -1.1934565   1.26548033]
 [-1.43325843  0.23585714 -2.34997119]
 [ 0.93131644 -0.29082541 -0.45783313]
 [-0.40005523 -0.84239668 -0.56433677]]
Random integer vector: [ 2 66 30 20 33 73 21 71 21  4]

Random integer matrix
[[86 74 36 74]
 [20 20  4 33]
 [99 44 34 34]
 [21 27 11 97]]

20 samples drawn from a dice throw: [1 4 5 6 4 5 2 6 4 3 4 2 3 2 2 2 4 1 5 2]


### 8.Find the nearest value from a given number in an array using NumPy.

In [105]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

import numpy as np
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]


array = np.random.randint(1,12,5)
print(array)
value = 10

print(find_nearest(array, value))



[ 2  2 10  3  7]
10


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [83]:
import numpy as np
a = np.array([[0, 0, 0],
              [0, 1, 2],
              [0, 2, 4]])
print(a)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
